### ISSUE TITLE
Modify iharm for the user defined arbitrary spacetime

### ISSUE THREAD

**Issue by osokoliuk** [AFD-Illinois/iharm2d_v3#2]
Hi. Recently I installed and tried some models of ihard2d GRMHD code. It is very interesting code. However, I have a question. Is it possible to somehow define and use for GRMHD simulations (generally, I only need the model for accreting torus) user defined spacetime? For example the one for Morris-Thorne traversable wormhole solution?

**Comment by c-prather** [comment]
Hi!
In theory, `iharm` should support any analytic stationary spacetime.  This is defined through the covariant metric in coordinates.c, e.g. for a [Kerr torus](https://github.com/AFD-Illinois/iharm2d_v3/blob/master/prob:kerr_torus/coordinates.c).  `iharm` will perform the metric derivatives numerically and calculate the resulting connection coefficients.

However, changing the spacetime could require adjustments to the initial conditions, boundaries, and floor values for the simulation in order to keep it stable -- I'd imagine the initial torus solution especially might change significantly.  While the necessary floor and boundary values are pretty established for Kerr black holes (and nearby alternative theories of gravity), as far as I know this group has not tried something so exotic as a wormhole solution -- so, while we can answer basic questions about the code, you would still need to debug any of these sorts of issues that crop up in your spacetime.
